name: Basic Node
on:
  workflow_dispatch:
env:
  FILE: test.js

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Setup NodeJS
        uses: actions/setup-node@v4

      - name: Check current Directory
        run: echo
      - name: Execute JS FILE
        run: "node ${{env.FILE}}"
